codecov:
  token: 33177989-0bbc-4dfb-8310-90d00b97c75a
  bot: "codecov-io"
coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 0%
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
        branches: 
          - master
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: true