codecov:
  token: secret:8WmEPiq9RctAoDGEtQ+4PGyfeWp4wSKvB/aboE9JQ8APJM+Lup1SxpFZsrZSND9iKunCnY+OoWPtP09gtDCzwODOnmPwpiJEyX2v/j9mmxs=
  bot: "codecov-io"
coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0%
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
        branches: 
          - master
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: true